### PR TITLE
Move BandedMatrices+BlockArrays to BlockArray extension

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by jishnub** [comment]
Let's create a release-0.13 branch, as this would simplify collecting all the changes.

**Comment by dlfivefifty** [comment]
Done. But what else is going in release-0.13?

**Comment by jishnub** [comment]
There are some other minor changes that might be useful, like not exporting `Zeros/Ones/Fill/Block` and asking users to import these from the corresponding packages.

**Comment by dlfivefifty** [comment]
What's wrong with exporting them?

**Comment by jishnub** [comment]
It just makes the package more prone to breakages, as breaking changes upstream get translated to this package as well, which shouldn't be the case usually.

**Comment by dlfivefifty** [comment]
ok I see your point

**Pull request merged**
